const DISCIPLINES = [
  { name: 'Mechanical', code: 'MECH' },
  { name: 'Electrical', code: 'ELEC' },
  { name: 'Instrumentation', code: 'INST' },
  { name: 'Civil', code: 'CIVL' },
  { name: 'Inspection', code: 'INSP' },
  { name: 'Scaffolding', code: 'SCAF' },
  { name: 'Painting', code: 'PNT' },
  { name: 'Insulation', code: 'INSUL' },
  { name: 'Cleaning', code: 'CLN' },
  { name: 'QA/QC', code: 'QAQC' },
] as const;

const ACTIONS: Record<string, string[]> = {
  MECH: [
    'Isolate & Drain',
    'Blind Installation',
    'Blind Removal',
    'Unbolt Flanges',
    'Pull Bundle',
    'Insert Bundle',
    'Overhaul Rotor',
    'Replace Mechanical Seal',
    'Align Coupling',
    'Bearing Replacement',
    'Hydrotest',
    'Box-up',
    'Torque Flanges',
    'Leak Test',
    'Commission',
    'Valve Overhaul',
    'PSV Removal',
    'PSV Installation',
    'Gasket Replacement',
    'Pipe Spool Replacement',
    'Support Modification',
    'Steam Trap Service',
    'Expansion Joint Replace',
    'Crane Lift Setup',
    'Rigging Check',
  ],
  ELEC: [
    'LOTO Electrical',
    'Motor Megger Test',
    'Motor Disconnect',
    'Motor Reconnect',
    'Cable Glanding Check',
    'MCC Bucket Service',
    'Transformer Oil Sample',
    'Earth Continuity Test',
    'Heater Element Check',
    'VFD Parameter Backup',
    'Lighting Circuit Test',
    'UPS Battery Check',
    'Switchgear IR Test',
    'Soft Starter Check',
    'Ex-d Enclosure Inspection',
    'Cable Tray Repair',
    'Motor No-Load Run',
    'Polarization Index',
    'CT/PT Verification',
    'Panel Label Update',
    'Hazardous Area Audit',
    'Emergency Generator Test',
    'Busbar Torque Check',
    'Relay Secondary Injection',
    'Power Restoration',
  ],
  INST: [
    'Transmitter Calibration',
    'Control Valve Stroke',
    'Positioner Calibration',
    'Impulse Line Blowdown',
    'Analyzer Span Check',
    'Orifice Plate Inspection',
    'Thermocouple Replace',
    'Junction Box Inspection',
    'Loop Check Cold',
    'Loop Check Hot',
    'DCS I/O Verification',
    'ESD Function Test',
    'Interlock Bypass Log',
    'Flow Meter Prove',
    'Level Switch Test',
    'Pressure Gauge Calibrate',
    'Solenoid Valve Replace',
    'Air Supply Regulator Set',
    'Fire & Gas Detector Test',
    'Marshalling Cabinet Clean',
    'Soft Tag Update',
    'Cause & Effect Verify',
    'Smart Device Download',
    'Tube Fitting Remake',
    'Instrument Air Leak Check',
  ],
  CIVL: [
    'Concrete Repair',
    'Grout Pump Base',
    'Structural Steel Weld',
    'Platform Grating Repair',
    'Handrail Modification',
    'Pipe Rack Bolt Check',
    'Foundation Crack Seal',
    'Fireproofing Repair',
    'Drain Channel Clean',
    'Paving Repair',
    'Anchor Bolt Replace',
    'Access Stair Repair',
    'Catch Basin Clean',
    'Cable Trench Cover',
    'Blast Wall Inspection',
    'Road Crossing Plate',
    'Culvert Clearance',
    'Building HVAC Filter',
    'Roof Leak Repair',
    'Fence Gate Adjust',
    'Sump Pump Civil Pad',
    'Equipment Pedestal Chip',
    'Expansion Joint Seal',
    'Manhole Cover Replace',
    'Site Survey Mark-up',
  ],
  INSP: [
    'External Visual Inspection',
    'Internal Visual Inspection',
    'UT Thickness Survey',
    'Radiography RT',
    'MPI Crack Detection',
    'DPT Dye Penetrant',
    'Hardness Test',
    'Positive Material ID',
    'Corrosion Coupon Pull',
    'Nozzle Inspection',
    'Tray Inspection',
    'Bundle Tube Inspection',
    'Weld Visual VT',
    'Hydrotest Witness',
    'Pneumatic Test Witness',
    'Flange Face Inspection',
    'Bolt Tension Audit',
    'CUI Inspection',
    'Tank Floor Scan',
    'Column Shell UT',
    'Fired Heater Tube UT',
    'Piping Isometric Walkdown',
    'Relief Device Inspection',
    'Structural Thickness Check',
    'Final Clearance Inspection',
  ],
  SCAF: [
    'Scaffold Erect',
    'Scaffold Modify',
    'Scaffold Dismantle',
    'Scaffold Tag Inspect',
    'Birdcage Scaffold',
    'Hanging Scaffold',
    'Tower Scaffold',
    'Mobile Tower Erect',
    'Scaffold Load Check',
    'Weather Protection Install',
    'Scaffold Board Replace',
    'Toe Board Install',
    'Ladder Access Fix',
    'Scaffold Hand-over',
    'Scaffold Weekly Inspect',
    'Confined Space Access',
    'Scaffold Tie-in Check',
    'Debris Net Install',
    'Scaffold Material Stage',
    'Scaffold Material Return',
    'Cantilever Scaffold',
    'Internal Vessel Scaffold',
    'Pipe Rack Access',
    'Heater Box Scaffold',
    'Emergency Scaffold Repair',
  ],
  PNT: [
    'Surface Prep Blast',
    'Primer Application',
    'Intermediate Coat',
    'Finish Coat',
    'DFT Measurement',
    'Touch-up Paint',
    'Stripe Coat Welds',
    'Tank External Paint',
    'Pipe Colour Coding',
    'Stencil Equipment Tag',
    'Fireproof Paint Repair',
    'Galvanize Touch-up',
    'Floor Coating',
    'Containment Paint',
    'Heat-Resistant Paint',
    'Under Insulation Paint',
    'Holiday Detection',
    'Paint System Spec Check',
    'Mask & Protect',
    'Demobilize Paint Gear',
    'Scaffold Paint Access',
    'Colour Band Update',
    'Corrosion Spot Treat',
    'Final Coat Cure Check',
    'Paint Waste Disposal',
  ],
  INSUL: [
    'Insulation Removal',
    'Insulation Install',
    'Cladding Install',
    'Personal Protection Insul',
    'CUI Insulation Replace',
    'Removable Jacket Fit',
    'Valve Box Insulation',
    'Flange Insulation Box',
    'Cold Insulation Repair',
    'Hot Insulation Repair',
    'Insulation Support Ring',
    'Weather Barrier Seal',
    'Insulation Thickness Check',
    'Asbestos Survey Hold',
    'Insulation Material Stage',
    'Insulation Waste Bag',
    'Steam Line Re-insulate',
    'Exchanger Insulation',
    'Vessel Head Insulation',
    'Pipe Elbow Insulation',
    'Insulation QC Inspect',
    'Cladding Screw Replace',
    'Insulation Banding',
    'Temporary Insulation',
    'Demobilize Insulation',
  ],
  CLN: [
    'Chemical Cleaning',
    'High Pressure Jetting',
    'Steam Cleaning',
    'Manual Scraping',
    'Catalyst Unloading',
    'Catalyst Loading',
    'Pigging Operation',
    'Tank Cleaning',
    'Vessel Degassing',
    'Oil Flush',
    'Lube Oil Flush',
    'Air Blowing',
    'Nitrogen Purge',
    'Water Flush',
    'Desludging',
    'Heat Exchanger Clean',
    'Air Cooler Fin Clean',
    'Sewer Line Clean',
    'Oily Water Separator Clean',
    'Confined Space Clean',
    'Passivation',
    'Neutralization',
    'Waste Manifest',
    'Final Cleanliness Check',
    'Housekeeping Sweep',
  ],
  QAQC: [
    'ITP Hold Point',
    'ITP Witness Point',
    'Material Receiving Inspect',
    'Weld Procedure Review',
    'Welder Qualification Check',
    'NDT Coordination',
    'Punch List Raise',
    'Punch List Clear',
    'MDR Compilation',
    'As-Built Markup',
    'Calibration Certificate Check',
    'Torque Chart Verify',
    'Flange Management Audit',
    'Blind Register Audit',
    'LOTO Audit',
    'Permit Compliance Check',
    'Final Document Review',
    'Turnover Package Prep',
    'Non-Conformance Raise',
    'NCR Close-out',
    'Vendor FAT Witness',
    'Site SAT Witness',
    'Pressure Test Package',
    'QA Walkdown',
    'Release for Operation',
  ],
};

export { DISCIPLINES };

export function buildActivityCodes(): {
  name: string;
  code: string;
  disciplineCode: string;
  duration_hours: number;
  description: string;
  phase: string;
}[] {
  const out: {
    name: string;
    code: string;
    disciplineCode: string;
    duration_hours: number;
    description: string;
    phase: string;
  }[] = [];
  let n = 1;
  for (const d of DISCIPLINES) {
    for (const action of ACTIONS[d.code]) {
      const code = `ACT-${d.code}-${String(n).padStart(4, '0')}`;
      out.push({
        name: `${d.name} — ${action}`,
        code,
        disciplineCode: d.code,
        duration_hours: 2 + ((n * 3) % 16),
        description: `${action} for ${d.name.toLowerCase()} discipline during turnaround execution.`,
        phase: n % 3 === 0 ? 'Execution' : n % 3 === 1 ? 'Preparation' : 'Commissioning',
      });
      n++;
    }
  }
  // pad to ≥250 if needed
  while (out.length < 250) {
    const d = DISCIPLINES[out.length % DISCIPLINES.length];
    const code = `ACT-${d.code}-${String(n).padStart(4, '0')}`;
    out.push({
      name: `${d.name} — Supplemental Task ${n}`,
      code,
      disciplineCode: d.code,
      duration_hours: 4,
      description: `Supplemental ${d.name.toLowerCase()} turnaround activity.`,
      phase: 'Execution',
    });
    n++;
  }
  return out;
}
