export const CERTIFICATE_TEMPLATES = [
  { cert_type: 'Hydrotest', cert_name: 'Pressure Test Certificate — Piping', equipment_types: ['Gate Valve', 'Shell & Tube Heat Exchanger'] },
  { cert_type: 'Hydrotest', cert_name: 'Pressure Test Certificate — Vessel', equipment_types: ['Pressure Vessel', 'Drum / Knockout Drum'] },
  { cert_type: 'Calibration', cert_name: 'PSV Bench Test Certificate', equipment_types: ['PSV / PRV'] },
  { cert_type: 'Calibration', cert_name: 'Transmitter Calibration Certificate', equipment_types: ['Transmitter'] },
  { cert_type: 'Calibration', cert_name: 'Control Valve Stroke Certificate', equipment_types: ['Control Valve'] },
  { cert_type: 'Inspection', cert_name: 'Column Internal Inspection Certificate', equipment_types: ['Distillation Column'] },
  { cert_type: 'Inspection', cert_name: 'Exchanger Bundle Inspection Report', equipment_types: ['Shell & Tube Heat Exchanger'] },
  { cert_type: 'Inspection', cert_name: 'Tank Internal Inspection Certificate', equipment_types: ['Storage Tank'] },
  { cert_type: 'Alignment', cert_name: 'Pump–Motor Alignment Certificate', equipment_types: ['Centrifugal Pump', 'Induction Motor'] },
  { cert_type: 'Electrical', cert_name: 'Motor Megger Test Certificate', equipment_types: ['Induction Motor'] },
  { cert_type: 'Electrical', cert_name: 'Transformer Oil Test Certificate', equipment_types: ['Transformer'] },
  { cert_type: 'NDT', cert_name: 'UT Thickness Survey Certificate', equipment_types: ['Pressure Vessel', 'Distillation Column'] },
  { cert_type: 'NDT', cert_name: 'Radiography Interpretation Report', equipment_types: ['Gate Valve', 'Pressure Vessel'] },
  { cert_type: 'Welding', cert_name: 'Weld Visual Inspection Certificate', equipment_types: ['Pressure Vessel'] },
  { cert_type: 'Cleaning', cert_name: 'Chemical Cleaning Completion Certificate', equipment_types: ['Shell & Tube Heat Exchanger', 'Reactor'] },
  { cert_type: 'Catalyst', cert_name: 'Catalyst Loading Certificate', equipment_types: ['Reactor'] },
  { cert_type: 'Safety', cert_name: 'Confined Space Entry Clearance', equipment_types: ['Distillation Column', 'Storage Tank'] },
  { cert_type: 'Safety', cert_name: 'LOTO Verification Certificate', equipment_types: ['Centrifugal Pump', 'Induction Motor'] },
  { cert_type: 'Material', cert_name: 'Material Receiving Inspection Certificate', equipment_types: ['Gate Valve', 'Control Valve'] },
  { cert_type: 'Turnover', cert_name: 'System Mechanical Completion Certificate', equipment_types: ['Distillation Column', 'Reactor'] },
  { cert_type: 'Painting', cert_name: 'DFT Coating Inspection Certificate', equipment_types: ['Storage Tank', 'Pressure Vessel'] },
  { cert_type: 'Insulation', cert_name: 'Insulation Completion Certificate', equipment_types: ['Shell & Tube Heat Exchanger'] },
  { cert_type: 'Compressor', cert_name: 'Compressor Mechanical Run Certificate', equipment_types: ['Centrifugal Compressor'] },
  { cert_type: 'Heater', cert_name: 'Fired Heater Tube Inspection Certificate', equipment_types: ['Fired Heater'] },
];

export const PRINT_TEMPLATE_PRESETS = [
  { name: 'Workpack Cover — IOCL Orange', accent: '#E8701A', bg: '#0D2137' },
  { name: 'Workpack Cover — HMEL Blue', accent: '#0056A4', bg: '#0A1628' },
  { name: 'Workpack Cover — RIL Burgundy', accent: '#8B1E3F', bg: '#1A0A10' },
  { name: 'ITP Package Header', accent: '#1F6F5B', bg: '#0D2137' },
  { name: 'Blind Register Print', accent: '#C45C26', bg: '#1A1A1A' },
  { name: 'Daily Progress Report', accent: '#2E5A88', bg: '#0D2137' },
  { name: 'Permit to Work Summary', accent: '#B33A3A', bg: '#1A0A0A' },
  { name: 'QA Punch List', accent: '#5B4B8A', bg: '#120F1A' },
  { name: 'Material Issue Slip', accent: '#3D6B4F', bg: '#0D1A12' },
  { name: 'Scaffold Handover', accent: '#8A6D3B', bg: '#1A140A' },
  { name: 'Hydrotest Pack Cover', accent: '#1E5F8A', bg: '#0A1520' },
  { name: 'PSV Certificate Pack', accent: '#6B3A5B', bg: '#140A12' },
  { name: 'Manpower Histogram Print', accent: '#2F6F6F', bg: '#0A1A1A' },
  { name: 'Lookahead Schedule', accent: '#4A6FA5', bg: '#0D1520' },
  { name: 'Turnover Dossier Cover', accent: '#3A5A40', bg: '#0A140C' },
  { name: 'Contractor Daily Report', accent: '#7A4E2D', bg: '#1A1008' },
  { name: 'Safety Observation Log', accent: '#A33B3B', bg: '#1A0A0A' },
  { name: 'Flange Management Sheet', accent: '#4E6E8A', bg: '#0C141C' },
  { name: 'Catalyst Handling Pack', accent: '#5A4A8A', bg: '#100A1A' },
  { name: 'Final Box-up Checklist', accent: '#2A6B4E', bg: '#0A1A12' },
  { name: 'Night Shift Briefing', accent: '#3B4A6B', bg: '#0A0E1A' },
  { name: 'SIMOPS Coordination Sheet', accent: '#8A3B5A', bg: '#1A0A10' },
];
