export const RESOURCE_TYPES = [
  { name: 'Mechanical Fitter', code: 'RES-MFIT', discipline: 'MECH' },
  { name: 'Welder (SMAW/GTAW)', code: 'RES-WELD', discipline: 'MECH' },
  { name: 'Rigging Crew', code: 'RES-RIG', discipline: 'MECH' },
  { name: 'Scaffold Team', code: 'RES-SCAF', discipline: 'SCAF' },
  { name: 'Instrument Technician', code: 'RES-INST', discipline: 'INST' },
  { name: 'Electrician', code: 'RES-ELEC', discipline: 'ELEC' },
  { name: 'Mobile Crane 50T', code: 'RES-CRN50', discipline: 'MECH' },
  { name: 'Hydra Crane', code: 'RES-HYDRA', discipline: 'MECH' },
  { name: 'Forklift 3T', code: 'RES-FORK', discipline: 'MECH' },
  { name: 'QA/QC Inspector', code: 'RES-QAQC', discipline: 'QAQC' },
  { name: 'Safety Officer', code: 'RES-SAFE', discipline: 'INSP' },
  { name: 'Painter Crew', code: 'RES-PNT', discipline: 'PNT' },
  { name: 'Insulation Crew', code: 'RES-INSUL', discipline: 'INSUL' },
  { name: 'Cleaning Crew', code: 'RES-CLN', discipline: 'CLN' },
  { name: 'Civil Mason', code: 'RES-CIVL', discipline: 'CIVL' },
  { name: 'NDT Technician', code: 'RES-NDT', discipline: 'INSP' },
  { name: 'Millwright', code: 'RES-MILL', discipline: 'MECH' },
  { name: 'Pipe Fitter', code: 'RES-PIPE', discipline: 'MECH' },
  { name: 'Vacuum Truck', code: 'RES-VAC', discipline: 'CLN' },
  { name: 'Manlift / Boom Lift', code: 'RES-LIFT', discipline: 'SCAF' },
];

const UDF_BASE: { name: string; code: string; type: string }[] = [
  { name: 'Work Permit Number', code: 'UDF_PERMIT_NO', type: 'TEXT' },
  { name: 'LOTO Certificate Number', code: 'UDF_LOTO_NO', type: 'TEXT' },
  { name: 'Gas Test Result', code: 'UDF_GAS_TEST', type: 'SELECT' },
  { name: 'Confined Space Entry', code: 'UDF_CSE', type: 'BOOLEAN' },
  { name: 'Hot Work Required', code: 'UDF_HOT_WORK', type: 'BOOLEAN' },
  { name: 'Radiography Window', code: 'UDF_RT_WINDOW', type: 'DATE' },
  { name: 'Crane Lift Plan Ref', code: 'UDF_LIFT_PLAN', type: 'TEXT' },
  { name: 'Blind Register ID', code: 'UDF_BLIND_ID', type: 'TEXT' },
  { name: 'Flange Class', code: 'UDF_FLANGE_CLASS', type: 'SELECT' },
  { name: 'Gasket Type', code: 'UDF_GASKET', type: 'SELECT' },
  { name: 'Bolt Spec', code: 'UDF_BOLT_SPEC', type: 'TEXT' },
  { name: 'Torque Value (Nm)', code: 'UDF_TORQUE', type: 'NUMBER' },
  { name: 'Hydrotest Pressure (barg)', code: 'UDF_HYDRO_P', type: 'NUMBER' },
  { name: 'Hold Point Type', code: 'UDF_HOLD_TYPE', type: 'SELECT' },
  { name: 'Witness Required', code: 'UDF_WITNESS', type: 'BOOLEAN' },
  { name: 'ITP Clause', code: 'UDF_ITP', type: 'TEXT' },
  { name: 'Contractor Gang', code: 'UDF_GANG', type: 'TEXT' },
  { name: 'Night Shift Allowed', code: 'UDF_NIGHT', type: 'BOOLEAN' },
  { name: 'Scaffold Tag Number', code: 'UDF_SCAF_TAG', type: 'TEXT' },
  { name: 'Insulation Spec', code: 'UDF_INSUL_SPEC', type: 'TEXT' },
  { name: 'Paint System', code: 'UDF_PAINT_SYS', type: 'SELECT' },
  { name: 'DFT Required (µm)', code: 'UDF_DFT', type: 'NUMBER' },
  { name: 'NDT Method', code: 'UDF_NDT', type: 'SELECT' },
  { name: 'Material Heat Number', code: 'UDF_HEAT_NO', type: 'TEXT' },
  { name: 'WPS Number', code: 'UDF_WPS', type: 'TEXT' },
  { name: 'Welder ID', code: 'UDF_WELDER', type: 'TEXT' },
  { name: 'Spare Parts Kit', code: 'UDF_SPARE_KIT', type: 'TEXT' },
  { name: 'OEM Manual Section', code: 'UDF_OEM_SEC', type: 'TEXT' },
  { name: 'P&ID Drawing Number', code: 'UDF_PID', type: 'TEXT' },
  { name: 'Isometric Number', code: 'UDF_ISO', type: 'TEXT' },
  { name: 'Method Statement Ref', code: 'UDF_MS', type: 'TEXT' },
  { name: 'JSA Reference', code: 'UDF_JSA', type: 'TEXT' },
  { name: 'PPE Category', code: 'UDF_PPE', type: 'SELECT' },
  { name: 'Simultaneous Operations', code: 'UDF_SIMOPS', type: 'BOOLEAN' },
  { name: 'System Owner', code: 'UDF_OWNER', type: 'TEXT' },
  { name: 'Priority Rank', code: 'UDF_PRIORITY', type: 'SELECT' },
  { name: 'Estimated Manhours', code: 'UDF_MH', type: 'NUMBER' },
  { name: 'Crew Size', code: 'UDF_CREW', type: 'NUMBER' },
  { name: 'Weather Sensitive', code: 'UDF_WEATHER', type: 'BOOLEAN' },
  { name: 'Catalyst Batch ID', code: 'UDF_CAT_BATCH', type: 'TEXT' },
  { name: 'Chemical Cleaning Recipe', code: 'UDF_CHEM', type: 'TEXT' },
  { name: 'Leak Class', code: 'UDF_LEAK', type: 'SELECT' },
  { name: 'Alignment Tolerance (mm)', code: 'UDF_ALIGN', type: 'NUMBER' },
  { name: 'Vibration Baseline', code: 'UDF_VIB', type: 'NUMBER' },
  { name: 'Oil Sample Lab Ref', code: 'UDF_OIL_LAB', type: 'TEXT' },
  { name: 'Calibration Due Date', code: 'UDF_CAL_DUE', type: 'DATE' },
  { name: 'Ex Area Classification', code: 'UDF_EX_AREA', type: 'SELECT' },
  { name: 'SIL Function', code: 'UDF_SIL', type: 'TEXT' },
  { name: 'Bypass Authority', code: 'UDF_BYPASS', type: 'TEXT' },
  { name: 'Turnover Package ID', code: 'UDF_TO_PKG', type: 'TEXT' },
];

export function buildUdfDefinitions() {
  const out = [...UDF_BASE];
  let i = 1;
  while (out.length < 55) {
    out.push({
      name: `Turnaround Control Field ${i}`,
      code: `UDF_TA_CTRL_${String(i).padStart(2, '0')}`,
      type: i % 2 === 0 ? 'TEXT' : 'NUMBER',
    });
    i++;
  }
  return out.slice(0, 55);
}
