#!/bin/bash
# ============================================================================
# Syority VPS bootstrap — run ON THE SERVER as root (via sudo).
# Expects the code bundle at /tmp/syority-code.tar.gz (uploaded by
# migrate-to-vps.ps1). Idempotent: safe to re-run.
#
#   sudo bash /tmp/vps-setup.sh
# ============================================================================
set -e

APP_DIR="/var/www/syority"
PUBLIC_IP="${PUBLIC_IP:-66.116.246.67}"
DEPLOY_USER="${SUDO_USER:-$(whoami)}"

echo "==> 1/6 Installing Docker (if missing)..."
if ! command -v docker > /dev/null 2>&1; then
  curl -fsSL https://get.docker.com | sh
fi
if ! docker compose version > /dev/null 2>&1; then
  apt-get update -qq && apt-get install -y -qq docker-compose-plugin
fi
usermod -aG docker "$DEPLOY_USER" || true
docker compose version

echo "==> 2/6 Configuring firewall..."
if command -v ufw > /dev/null 2>&1; then
  ufw allow OpenSSH > /dev/null
  ufw allow 80/tcp  > /dev/null
  ufw allow 443/tcp > /dev/null
  ufw --force enable
  ufw status | head -10
fi

echo "==> 3/6 Extracting application code to $APP_DIR..."
if [ ! -f /tmp/syority-code.tar.gz ]; then
  echo "❌ /tmp/syority-code.tar.gz not found. Upload it first."
  exit 1
fi
mkdir -p "$APP_DIR"
tar -xzf /tmp/syority-code.tar.gz -C "$APP_DIR"
chown -R "$DEPLOY_USER":"$DEPLOY_USER" "$APP_DIR"
cd "$APP_DIR"
# Strip Windows CRLF line endings that would break bash/env parsing
find scripts -name '*.sh' -exec sed -i 's/\r$//' {} + 2>/dev/null || true
sed -i 's/\r$//' .env.example 2>/dev/null || true
chmod +x scripts/*.sh

echo "==> 4/6 Creating .env (only if missing — existing config is never overwritten)..."
if [ ! -f .env ]; then
  ADMIN_PASSWORD="$(openssl rand -base64 12 | tr -d '/+=' | head -c 16)!Aa1"
  cat > .env << EOF
# Generated by vps-setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

# --- Database (docker network hostnames) ---
DATABASE_URL="postgresql://user:pass@db:5432/syority?schema=public"
REDIS_URL="redis://redis:6379"

# --- NextAuth ---
NEXTAUTH_URL="http://${PUBLIC_IP}"
NEXTAUTH_SECRET="$(openssl rand -base64 32)"

# --- Platform Admin (used by prisma/seed.ts) ---
PLATFORM_ADMIN_EMAIL="admin@syority.com"
PLATFORM_ADMIN_PASSWORD="${ADMIN_PASSWORD}"

# --- Encryption (exactly 32 chars — NEVER change once tenants store API keys) ---
ENCRYPTION_KEY="$(openssl rand -hex 16)"

# --- Deployment ---
# "_" = catch-all server_name for IP-only HTTP mode. Set a real domain +
# run scripts/init-letsencrypt.sh when switching to HTTPS.
DOMAIN="_"

# --- WhatsApp Webhook ---
WHATSAPP_VERIFY_TOKEN="$(openssl rand -hex 16)"

# --- File Storage ---
STORAGE_PROVIDER="local"

# --- Email (SMTP) — fill in to enable user invitations ---
SMTP_HOST=""
SMTP_PORT="587"
SMTP_USER=""
SMTP_PASSWORD=""
EMAIL_FROM="Syority Platform <noreply@syority.com>"

# --- AI — fill in to enable AI features ---
AI_MODEL="gemini-1.5-pro"
GEMINI_API_KEY=""
EOF
  chown "$DEPLOY_USER":"$DEPLOY_USER" .env && chmod 600 .env
  echo ""
  echo "  ┌──────────────────────────────────────────────────────┐"
  echo "  │  PLATFORM ADMIN LOGIN (save this now!)               │"
  echo "  │  Email:    admin@syority.com                         │"
  echo "  │  Password: ${ADMIN_PASSWORD}"
  echo "  └──────────────────────────────────────────────────────┘"
  echo ""
  FIRST_RUN=1
else
  echo "  .env already exists — keeping it."
  FIRST_RUN=0
fi

echo "==> 5/6 Building and deploying (this builds the Docker images — first run takes several minutes)..."
export COMPOSE_FILES="-f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.http.yml"
export SEED="$FIRST_RUN"
bash scripts/deploy.sh

echo "==> 6/6 Final checks..."
docker compose $COMPOSE_FILES ps
echo ""
echo "✅ Done. App: http://${PUBLIC_IP}"
echo "   Health:   http://${PUBLIC_IP}/api/health"
echo ""
echo "Next steps:"
echo "  • Log in with the platform admin credentials printed above (first run only)"
echo "  • Fill SMTP_* and GEMINI_API_KEY in ${APP_DIR}/.env, then rerun scripts/deploy.sh"
echo "  • When you have a domain: point DNS here, set DOMAIN in .env, run scripts/init-letsencrypt.sh,"
echo "    and redeploy WITHOUT docker-compose.http.yml"
